
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// Boss配置
/// </summary>
public sealed partial class Boss : Luban.BeanBase
{
    public Boss(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Name = _buf.ReadString();
        OriginalSymbol = _buf.ReadString();
        SourceRange = _buf.ReadString();
        SkillKey = _buf.ReadString();
        AnimationKey = _buf.ReadString();
        if(_buf.ReadBool()){ ResourcePath = _buf.ReadString(); } else { ResourcePath = null; }
        AttackAnimation = _buf.ReadString();
        if(_buf.ReadBool()){ FollowupAnimation = _buf.ReadString(); } else { FollowupAnimation = null; }
        IdleAnimation = _buf.ReadString();
        Timeline = global::GameConfig.boss.Timeline.DeserializeTimeline(_buf);
        Enabled = _buf.ReadBool();
        HealthMultiplier = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        ContactDamage = _buf.ReadInt();
        RewardGold = _buf.ReadInt();
        LogicalWidth = _buf.ReadFloat();
        LogicalHeight = _buf.ReadFloat();
    }

    public static Boss DeserializeBoss(ByteBuf _buf)
    {
        return new battle.Boss(_buf);
    }

    /// <summary>
    /// 键(主键)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 原始符号
    /// </summary>
    public readonly string OriginalSymbol;
    /// <summary>
    /// 源码区间
    /// </summary>
    public readonly string SourceRange;
    /// <summary>
    /// 技能键
    /// </summary>
    public readonly string SkillKey;
    /// <summary>
    /// 动画键
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string ResourcePath;
    /// <summary>
    /// 攻击动画
    /// </summary>
    public readonly string AttackAnimation;
    /// <summary>
    /// 后续动画
    /// </summary>
    public readonly string FollowupAnimation;
    /// <summary>
    /// 待机动画
    /// </summary>
    public readonly string IdleAnimation;
    /// <summary>
    /// 时间轴
    /// </summary>
    public readonly boss.Timeline Timeline;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// 生命倍率
    /// </summary>
    public readonly float HealthMultiplier;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 终点接触伤害
    /// </summary>
    public readonly int ContactDamage;
    /// <summary>
    /// 击杀金币
    /// </summary>
    public readonly int RewardGold;
    /// <summary>
    /// 逻辑宽度
    /// </summary>
    public readonly float LogicalWidth;
    /// <summary>
    /// 逻辑高度
    /// </summary>
    public readonly float LogicalHeight;
   
    public const int __ID__ = -796046589;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Timeline?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "name:" + Name + ","
        + "originalSymbol:" + OriginalSymbol + ","
        + "sourceRange:" + SourceRange + ","
        + "skillKey:" + SkillKey + ","
        + "animationKey:" + AnimationKey + ","
        + "resourcePath:" + ResourcePath + ","
        + "attackAnimation:" + AttackAnimation + ","
        + "followupAnimation:" + FollowupAnimation + ","
        + "idleAnimation:" + IdleAnimation + ","
        + "timeline:" + Timeline + ","
        + "enabled:" + Enabled + ","
        + "healthMultiplier:" + HealthMultiplier + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "contactDamage:" + ContactDamage + ","
        + "rewardGold:" + RewardGold + ","
        + "logicalWidth:" + LogicalWidth + ","
        + "logicalHeight:" + LogicalHeight + ","
        + "}";
    }
}
}

