
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// Boss配置
/// </summary>
public sealed partial class Boss : Luban.BeanBase
{
    public Boss(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ResName = _buf.ReadString();
        Name = _buf.ReadString();
        SkillId = _buf.ReadInt();
        AnimationKey = _buf.ReadString();
        if(_buf.ReadBool()){ ResourcePath = _buf.ReadString(); } else { ResourcePath = null; }
        AttackAnimation = _buf.ReadString();
        IdleAnimation = _buf.ReadString();
        Timeline = global::GameConfig.boss.Timeline.DeserializeTimeline(_buf);
        Enabled = _buf.ReadBool();
        HealthMultiplier = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        ContactDamage = _buf.ReadInt();
        RewardGold = _buf.ReadInt();
        LogicalWidth = _buf.ReadFloat();
        LogicalHeight = _buf.ReadFloat();
    }

    public static Boss DeserializeBoss(ByteBuf _buf)
    {
        return new battle.Boss(_buf);
    }

    /// <summary>
    /// 主键，Boss 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名，原主键，保留作溯源
    /// </summary>
    public readonly string ResName;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能 ID，引用 skill.Id，技能类别应为 boss
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// Spine 表现绑定键，必填，如 boss0
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// YooAsset Prefab 地址，非磁盘路径，如 ZhangLiang
    /// </summary>
    public readonly string ResourcePath;
    /// <summary>
    /// Spine 普通攻击动画名，如 attackliang
    /// </summary>
    public readonly string AttackAnimation;
    /// <summary>
    /// Spine 待机/移动循环动画名，如 goliang
    /// </summary>
    public readonly string IdleAnimation;
    /// <summary>
    /// 技能时间轴：effectAtMs（效果提交时刻）/ completeAtMs（完成时刻），后者必须大于前者
    /// </summary>
    public readonly boss.Timeline Timeline;
    /// <summary>
    /// 是否启用，只有启用 Boss 才允许进入正式计划
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// Boss 基础生命倍率
    /// </summary>
    public readonly float HealthMultiplier;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 到达终点造成的伤害
    /// </summary>
    public readonly int ContactDamage;
    /// <summary>
    /// 击杀金币
    /// </summary>
    public readonly int RewardGold;
    /// <summary>
    /// 逻辑宽度，用于中心、范围及表现定位
    /// </summary>
    public readonly float LogicalWidth;
    /// <summary>
    /// 逻辑高度
    /// </summary>
    public readonly float LogicalHeight;
   
    public const int __ID__ = -796046589;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Timeline?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "resName:" + ResName + ","
        + "name:" + Name + ","
        + "skillId:" + SkillId + ","
        + "animationKey:" + AnimationKey + ","
        + "resourcePath:" + ResourcePath + ","
        + "attackAnimation:" + AttackAnimation + ","
        + "idleAnimation:" + IdleAnimation + ","
        + "timeline:" + Timeline + ","
        + "enabled:" + Enabled + ","
        + "healthMultiplier:" + HealthMultiplier + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "contactDamage:" + ContactDamage + ","
        + "rewardGold:" + RewardGold + ","
        + "logicalWidth:" + LogicalWidth + ","
        + "logicalHeight:" + LogicalHeight + ","
        + "}";
    }
}
}

