
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// Buff类型配置
/// </summary>
public sealed partial class Buff : Luban.BeanBase
{
    public Buff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        if(_buf.ReadBool()){ Label = _buf.ReadString(); } else { Label = null; }
        Kind = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Channels = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Channels.Add(_e0);}}
        StackPolicy = _buf.ReadString();
        MaxStacks = _buf.ReadInt();
        if(_buf.ReadBool()){ ConflictKey = _buf.ReadString(); } else { ConflictKey = null; }
    }

    public static Buff DeserializeBuff(ByteBuf _buf)
    {
        return new battle.Buff(_buf);
    }

    /// <summary>
    /// 全局唯一 Buff 数字 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定英文键
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 中文显示名，可空
    /// </summary>
    public readonly string Label;
    /// <summary>
    /// 类别：0=Numeric 数值型 / 1=State 状态型 / 2=Custom 自定义处理器
    /// </summary>
    public readonly int Kind;
    /// <summary>
    /// 通道列表。Numeric：0攻击/1攻速/2范围/3移速/4最大生命/5当前生命/6缩放；State：0禁移动/1禁攻击/2改变选敌/3压制/4伤害脉冲/5击退脉冲/6移动锁定
    /// </summary>
    public readonly System.Collections.Generic.List<int> Channels;
    /// <summary>
    /// 叠层策略，严格填 Add / Refresh / Replace
    /// </summary>
    public readonly string StackPolicy;
    /// <summary>
    /// 最大层数，必须大于 0
    /// </summary>
    public readonly int MaxStacks;
    /// <summary>
    /// 冲突键，同键的其他 Buff 会被替换；无互斥需求留空
    /// </summary>
    public readonly string ConflictKey;
   
    public const int __ID__ = -796041239;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "label:" + Label + ","
        + "kind:" + Kind + ","
        + "channels:" + Luban.StringUtil.CollectionToString(Channels) + ","
        + "stackPolicy:" + StackPolicy + ","
        + "maxStacks:" + MaxStacks + ","
        + "conflictKey:" + ConflictKey + ","
        + "}";
    }
}
}

