
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 最简牌组配置(task 3.1 新增,spec 6.5 均匀四兵)
/// </summary>
public sealed partial class Deck : Luban.BeanBase
{
    public Deck(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
    }

    public static Deck DeserializeDeck(ByteBuf _buf)
    {
        return new battle.Deck(_buf);
    }

    /// <summary>
    /// 占位
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = -795997121;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}
}

