
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗经济配置
/// </summary>
public sealed partial class Economy : Luban.BeanBase
{
    public Economy(ByteBuf _buf) 
    {
        InitialGold = _buf.ReadInt();
        RefreshCostStart = _buf.ReadInt();
        RefreshCostIncrement = _buf.ReadInt();
        UnitBaseCost = _buf.ReadInt();
        HandSize = _buf.ReadInt();
        PlayerMaxHealth = _buf.ReadInt();
        OpponentMaxHealth = _buf.ReadInt();
    }

    public static Economy DeserializeEconomy(ByteBuf _buf)
    {
        return new battle.Economy(_buf);
    }

    public readonly int InitialGold;
    public readonly int RefreshCostStart;
    public readonly int RefreshCostIncrement;
    public readonly int UnitBaseCost;
    public readonly int HandSize;
    /// <summary>
    /// 玩家方最大生命
    /// </summary>
    public readonly int PlayerMaxHealth;
    /// <summary>
    /// 对手方最大生命
    /// </summary>
    public readonly int OpponentMaxHealth;
   
    public const int __ID__ = -194263320;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "initialGold:" + InitialGold + ","
        + "refreshCostStart:" + RefreshCostStart + ","
        + "refreshCostIncrement:" + RefreshCostIncrement + ","
        + "unitBaseCost:" + UnitBaseCost + ","
        + "handSize:" + HandSize + ","
        + "playerMaxHealth:" + PlayerMaxHealth + ","
        + "opponentMaxHealth:" + OpponentMaxHealth + ","
        + "}";
    }
}
}

