
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗经济配置
/// </summary>
public sealed partial class Economy : Luban.BeanBase
{
    public Economy(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        InitialGold = _buf.ReadInt();
        RefreshCostStart = _buf.ReadInt();
        RefreshCostIncrement = _buf.ReadInt();
        UnitBaseCost = _buf.ReadInt();
        HandSize = _buf.ReadInt();
    }

    public static Economy DeserializeEconomy(ByteBuf _buf)
    {
        return new battle.Economy(_buf);
    }

    /// <summary>
    /// 占位
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 开局金币
    /// </summary>
    public readonly int InitialGold;
    /// <summary>
    /// 首次刷新费用
    /// </summary>
    public readonly int RefreshCostStart;
    /// <summary>
    /// 每次刷新递增的费用
    /// </summary>
    public readonly int RefreshCostIncrement;
    /// <summary>
    /// 基础招募/单位费用
    /// </summary>
    public readonly int UnitBaseCost;
    /// <summary>
    /// 手牌数量
    /// </summary>
    public readonly int HandSize;
   
    public const int __ID__ = -194263320;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "initialGold:" + InitialGold + ","
        + "refreshCostStart:" + RefreshCostStart + ","
        + "refreshCostIncrement:" + RefreshCostIncrement + ","
        + "unitBaseCost:" + UnitBaseCost + ","
        + "handSize:" + HandSize + ","
        + "}";
    }
}
}

