
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class Economy : Luban.BeanBase
{
    public Economy(ByteBuf _buf) 
    {
        InitialGold = _buf.ReadInt();
        RefreshCostStart = _buf.ReadInt();
        RefreshCostIncrement = _buf.ReadInt();
        UnitBaseCost = _buf.ReadInt();
        HandSize = _buf.ReadInt();
    }

    public static Economy DeserializeEconomy(ByteBuf _buf)
    {
        return new battle.Economy(_buf);
    }

    /// <summary>
    /// 初始金币
    /// </summary>
    public readonly int InitialGold;
    /// <summary>
    /// 刷新起始消耗
    /// </summary>
    public readonly int RefreshCostStart;
    /// <summary>
    /// 刷新递增
    /// </summary>
    public readonly int RefreshCostIncrement;
    /// <summary>
    /// 单位基础消耗
    /// </summary>
    public readonly int UnitBaseCost;
    /// <summary>
    /// 手牌数
    /// </summary>
    public readonly int HandSize;
   
    public const int __ID__ = -194263320;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "initialGold:" + InitialGold + ","
        + "refreshCostStart:" + RefreshCostStart + ","
        + "refreshCostIncrement:" + RefreshCostIncrement + ","
        + "unitBaseCost:" + UnitBaseCost + ","
        + "handSize:" + HandSize + ","
        + "}";
    }
}
}

