
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 敌人类型配置(逆向快照)
/// </summary>
public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        if(_buf.ReadBool()){ TypeIndex = _buf.ReadInt(); } else { TypeIndex = null; }
        if(_buf.ReadBool()){ ResourceAddress = _buf.ReadString(); } else { ResourceAddress = null; }
    }

    public static Enemy DeserializeEnemy(ByteBuf _buf)
    {
        return new battle.Enemy(_buf);
    }

    /// <summary>
    /// 主键，敌人唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 普通敌人类型索引，必须唯一；留空表示技能召唤类，不进入普通波次目录
    /// </summary>
    public readonly int? TypeIndex;
    /// <summary>
    /// YooAsset Prefab 地址，如 Mob0，必须与 Prefab 文件名一致
    /// </summary>
    public readonly string ResourceAddress;
   
    public const int __ID__ = 1095086770;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "typeIndex:" + TypeIndex + ","
        + "resourceAddress:" + ResourceAddress + ","
        + "}";
    }
}
}

