
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Symbol = _buf.ReadString();
        if(_buf.ReadBool()){ Status = _buf.ReadString(); } else { Status = null; }
        if(_buf.ReadBool()){ Resource = _buf.ReadString(); } else { Resource = null; }
        if(_buf.ReadBool()){ Deferred = _buf.ReadString(); } else { Deferred = null; }
        {int n0 = _buf.ReadSize(); LevelMultipliers = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); LevelMultipliers.Add(_e0);}}
    }

    public static Enemy DeserializeEnemy(ByteBuf _buf)
    {
        return new battle.Enemy(_buf);
    }

    /// <summary>
    /// 键(主键)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 符号
    /// </summary>
    public readonly string Symbol;
    /// <summary>
    /// 状态
    /// </summary>
    public readonly string Status;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string Resource;
    /// <summary>
    /// 延迟项
    /// </summary>
    public readonly string Deferred;
    /// <summary>
    /// 等级倍数
    /// </summary>
    public readonly System.Collections.Generic.List<float> LevelMultipliers;
   
    public const int __ID__ = 1095086770;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "symbol:" + Symbol + ","
        + "status:" + Status + ","
        + "resource:" + Resource + ","
        + "deferred:" + Deferred + ","
        + "levelMultipliers:" + Luban.StringUtil.CollectionToString(LevelMultipliers) + ","
        + "}";
    }
}
}

