
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 敌人运行时数值(公式输入,task 3.1 新增)
/// </summary>
public sealed partial class EnemyStats : Luban.BeanBase
{
    public EnemyStats(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); HealthByWave = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); HealthByWave.Add(_e0);}}
        {int n0 = _buf.ReadSize(); EarlyRoundHealthMultipliers = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); EarlyRoundHealthMultipliers.Add(_e0);}}
        ContactDamage = _buf.ReadInt();
        RewardGold = _buf.ReadInt();
    }

    public static EnemyStats DeserializeEnemyStats(ByteBuf _buf)
    {
        return new battle.EnemyStats(_buf);
    }

    /// <summary>
    /// 敌人类型 ID，等于 enemy.Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 移动速度，逻辑像素/秒
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 各难度索引的基础血量列表，wave_plan.difficultyIndex 从 0 开始索引它
    /// </summary>
    public readonly System.Collections.Generic.List<int> HealthByWave;
    /// <summary>
    /// 前期波次额外血量倍率
    /// </summary>
    public readonly System.Collections.Generic.List<float> EarlyRoundHealthMultipliers;
    /// <summary>
    /// 抵达终点时对目标造成的伤害
    /// </summary>
    public readonly int ContactDamage;
    /// <summary>
    /// 击杀奖励金币
    /// </summary>
    public readonly int RewardGold;
   
    public const int __ID__ = -1258290931;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "healthByWave:" + Luban.StringUtil.CollectionToString(HealthByWave) + ","
        + "earlyRoundHealthMultipliers:" + Luban.StringUtil.CollectionToString(EarlyRoundHealthMultipliers) + ","
        + "contactDamage:" + ContactDamage + ","
        + "rewardGold:" + RewardGold + ","
        + "}";
    }
}
}

