
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 事件名映射
/// </summary>
public sealed partial class Event : Luban.BeanBase
{
    public Event(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
    }

    public static Event DeserializeEvent(ByteBuf _buf)
    {
        return new battle.Event(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = 1095325124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}
}

