
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class Event : Luban.BeanBase
{
    public Event(ByteBuf _buf) 
    {
        EventName = _buf.ReadString();
        Code = _buf.ReadString();
    }

    public static Event DeserializeEvent(ByteBuf _buf)
    {
        return new battle.Event(_buf);
    }

    /// <summary>
    /// 事件名(主键)
    /// </summary>
    public readonly string EventName;
    /// <summary>
    /// 事件码
    /// </summary>
    public readonly string Code;
   
    public const int __ID__ = 1095325124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "eventName:" + EventName + ","
        + "code:" + Code + ","
        + "}";
    }
}
}

