
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.battle
{ 
    public enum EWaveKind
    {
        /// <summary>
        /// 普通波
        /// </summary>
        Normal = 1,
        /// <summary>
        /// Boss 波
        /// </summary>
        Boss = 2,
    }

} 

