
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武将配置
/// </summary>
public sealed partial class General : Luban.BeanBase
{
    public General(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Family = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PartWords = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); PartWords.Add(_e0);}}
        Enabled = _buf.ReadBool();
        CombatArchetype = _buf.ReadString();
        RangeCells = _buf.ReadFloat();
        AttackDamage = _buf.ReadInt();
        AttackIntervalSeconds = _buf.ReadFloat();
        DamageMode = _buf.ReadString();
        TargetPolicy = _buf.ReadString();
        PrefabAddress = _buf.ReadString();
        AnimationKey = _buf.ReadString();
        if(_buf.ReadBool()){ ProjectileType = _buf.ReadString(); } else { ProjectileType = null; }
        ProjectileSpeed = _buf.ReadInt();
        PartRecruitWeight = _buf.ReadInt();
        if(_buf.ReadBool()){ SkillId = _buf.ReadInt(); } else { SkillId = null; }
    }

    public static General DeserializeGeneral(ByteBuf _buf)
    {
        return new battle.General(_buf);
    }

    /// <summary>
    /// 主键，武将唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 完整名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 姓氏字
    /// </summary>
    public readonly string Family;
    /// <summary>
    /// 名字拆字，严格两个不同的字，按顺序构成合成配方，如 张,飞
    /// </summary>
    public readonly System.Collections.Generic.List<string> PartWords;
    /// <summary>
    /// 是否进入本期配置快照与配方索引
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// 战斗原型，只能填 pike 或 bow
    /// </summary>
    public readonly string CombatArchetype;
    /// <summary>
    /// 攻击范围，格，必须为正
    /// </summary>
    public readonly float RangeCells;
    /// <summary>
    /// 1 级基础伤害，必须为正
    /// </summary>
    public readonly int AttackDamage;
    /// <summary>
    /// 基础攻击间隔，必须为正
    /// </summary>
    public readonly float AttackIntervalSeconds;
    /// <summary>
    /// 伤害模式：近战枪击 或 单体
    /// </summary>
    public readonly string DamageMode;
    /// <summary>
    /// 选敌策略，复用现有目标策略键
    /// </summary>
    public readonly string TargetPolicy;
    /// <summary>
    /// 武将 Prefab 地址，如 ZhangFei
    /// </summary>
    public readonly string PrefabAddress;
    /// <summary>
    /// Spine 待机动画名，当前统一为 zhan1
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// 投射物类型，仅远程武将必填，当前为 SimpleDynamicArrow；枪型留空
    /// </summary>
    public readonly string ProjectileType;
    /// <summary>
    /// 投射物速度，仅远程武将使用，当前 200；枪型填 0
    /// </summary>
    public readonly int ProjectileSpeed;
    /// <summary>
    /// 每个配方字加入玩家池的权重，必须大于 0
    /// </summary>
    public readonly int PartRecruitWeight;
    /// <summary>
    /// 主动技能 ID，引用 skill.Id
    /// </summary>
    public readonly int? SkillId;
   
    public const int __ID__ = 1636813202;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "family:" + Family + ","
        + "partWords:" + Luban.StringUtil.CollectionToString(PartWords) + ","
        + "enabled:" + Enabled + ","
        + "combatArchetype:" + CombatArchetype + ","
        + "rangeCells:" + RangeCells + ","
        + "attackDamage:" + AttackDamage + ","
        + "attackIntervalSeconds:" + AttackIntervalSeconds + ","
        + "damageMode:" + DamageMode + ","
        + "targetPolicy:" + TargetPolicy + ","
        + "prefabAddress:" + PrefabAddress + ","
        + "animationKey:" + AnimationKey + ","
        + "projectileType:" + ProjectileType + ","
        + "projectileSpeed:" + ProjectileSpeed + ","
        + "partRecruitWeight:" + PartRecruitWeight + ","
        + "skillId:" + SkillId + ","
        + "}";
    }
}
}

