
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武将配置
/// </summary>
public sealed partial class General : Luban.BeanBase
{
    public General(ByteBuf _buf) 
    {
        Index = _buf.ReadInt();
        Name = _buf.ReadString();
        Family = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PartWords = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); PartWords.Add(_e0);}}
        WeaponType = _buf.ReadInt();
        if(_buf.ReadBool()){ Status = _buf.ReadString(); } else { Status = null; }
    }

    public static General DeserializeGeneral(ByteBuf _buf)
    {
        return new battle.General(_buf);
    }

    /// <summary>
    /// 索引(主键)
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 姓氏
    /// </summary>
    public readonly string Family;
    /// <summary>
    /// 名字拆字
    /// </summary>
    public readonly System.Collections.Generic.List<string> PartWords;
    /// <summary>
    /// 武器类型
    /// </summary>
    public readonly int WeaponType;
    /// <summary>
    /// 状态
    /// </summary>
    public readonly string Status;
   
    public const int __ID__ = 1636813202;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "name:" + Name + ","
        + "family:" + Family + ","
        + "partWords:" + Luban.StringUtil.CollectionToString(PartWords) + ","
        + "weaponType:" + WeaponType + ","
        + "status:" + Status + ","
        + "}";
    }
}
}

