
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class Map : Luban.BeanBase
{
    public Map(ByteBuf _buf) 
    {
        GridWidth = _buf.ReadInt();
        GridHeight = _buf.ReadInt();
        Width = _buf.ReadInt();
        Height = _buf.ReadInt();
        MapIndex = _buf.ReadInt();
        if(_buf.ReadBool()){ Blocks = _buf.ReadString(); } else { Blocks = null; }
        {int n0 = _buf.ReadSize(); PlayerPath = new System.Collections.Generic.List<UnityEngine.Vector2Int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector2Int _e0;  _e0 = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf)); PlayerPath.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OpponentPath = new System.Collections.Generic.List<UnityEngine.Vector2Int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector2Int _e0;  _e0 = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf)); OpponentPath.Add(_e0);}}
    }

    public static Map DeserializeMap(ByteBuf _buf)
    {
        return new battle.Map(_buf);
    }

    /// <summary>
    /// 网格宽
    /// </summary>
    public readonly int GridWidth;
    /// <summary>
    /// 网格高
    /// </summary>
    public readonly int GridHeight;
    /// <summary>
    /// 宽
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 高
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 地图索引
    /// </summary>
    public readonly int MapIndex;
    /// <summary>
    /// 阻挡点
    /// </summary>
    public readonly string Blocks;
    /// <summary>
    /// 玩家路径
    /// </summary>
    public readonly System.Collections.Generic.List<UnityEngine.Vector2Int> PlayerPath;
    /// <summary>
    /// 对手路径
    /// </summary>
    public readonly System.Collections.Generic.List<UnityEngine.Vector2Int> OpponentPath;
   
    public const int __ID__ = 2052541190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "gridWidth:" + GridWidth + ","
        + "gridHeight:" + GridHeight + ","
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "mapIndex:" + MapIndex + ","
        + "blocks:" + Blocks + ","
        + "playerPath:" + Luban.StringUtil.CollectionToString(PlayerPath) + ","
        + "opponentPath:" + Luban.StringUtil.CollectionToString(OpponentPath) + ","
        + "}";
    }
}
}

