
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 地图配置
/// </summary>
public sealed partial class Map : Luban.BeanBase
{
    public Map(ByteBuf _buf) 
    {
        GridWidth = _buf.ReadInt();
        GridHeight = _buf.ReadInt();
        Width = _buf.ReadInt();
        Height = _buf.ReadInt();
        MapIndex = _buf.ReadInt();
        if(_buf.ReadBool()){ Blocks = _buf.ReadString(); } else { Blocks = null; }
        {int n0 = _buf.ReadSize(); PlayerPath = new System.Collections.Generic.List<UnityEngine.Vector2Int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector2Int _e0;  _e0 = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf)); PlayerPath.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OpponentPath = new System.Collections.Generic.List<UnityEngine.Vector2Int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector2Int _e0;  _e0 = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf)); OpponentPath.Add(_e0);}}
        CellWidth = _buf.ReadInt();
        CellHeight = _buf.ReadInt();
        MapCount = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Grid = new System.Collections.Generic.List<System.Collections.Generic.List<string>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<string> _e0;  {int n1 = _buf.ReadSize(); _e0 = new System.Collections.Generic.List<string>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { string _e1;  _e1 = _buf.ReadString(); _e0.Add(_e1);}} Grid.Add(_e0);}}
        PlayerEntry = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf));
        PlayerStart = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf));
        PlayerEnd = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf));
        OpponentEntry = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf));
        OpponentStart = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf));
        OpponentEnd = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf));
        {int n0 = _buf.ReadSize(); RouteMarkers = new System.Collections.Generic.List<UnityEngine.Vector2Int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector2Int _e0;  _e0 = ExternalTypeUtil.NewVector2Int(global::GameConfig.vector2int.Deserializevector2int(_buf)); RouteMarkers.Add(_e0);}}
        EnemyTypeIndex = _buf.ReadInt();
        Name = _buf.ReadString();
        ResourceAddress = _buf.ReadString();
    }

    public static Map DeserializeMap(ByteBuf _buf)
    {
        return new battle.Map(_buf);
    }

    public readonly int GridWidth;
    public readonly int GridHeight;
    public readonly int Width;
    public readonly int Height;
    public readonly int MapIndex;
    public readonly string Blocks;
    public readonly System.Collections.Generic.List<UnityEngine.Vector2Int> PlayerPath;
    public readonly System.Collections.Generic.List<UnityEngine.Vector2Int> OpponentPath;
    /// <summary>
    /// 格子像素宽
    /// </summary>
    public readonly int CellWidth;
    /// <summary>
    /// 格子像素高
    /// </summary>
    public readonly int CellHeight;
    /// <summary>
    /// 地图总数
    /// </summary>
    public readonly int MapCount;
    /// <summary>
    /// 列优先 grid[x][y] 格子编码 kind_lane
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<string>> Grid;
    /// <summary>
    /// 玩家入口坐标
    /// </summary>
    public readonly UnityEngine.Vector2Int PlayerEntry;
    /// <summary>
    /// 玩家路径起点
    /// </summary>
    public readonly UnityEngine.Vector2Int PlayerStart;
    /// <summary>
    /// 玩家路径终点
    /// </summary>
    public readonly UnityEngine.Vector2Int PlayerEnd;
    /// <summary>
    /// 对手入口坐标
    /// </summary>
    public readonly UnityEngine.Vector2Int OpponentEntry;
    /// <summary>
    /// 对手路径起点
    /// </summary>
    public readonly UnityEngine.Vector2Int OpponentStart;
    /// <summary>
    /// 对手路径终点
    /// </summary>
    public readonly UnityEngine.Vector2Int OpponentEnd;
    /// <summary>
    /// 表现层路径标记(含越界标记)
    /// </summary>
    public readonly System.Collections.Generic.List<UnityEngine.Vector2Int> RouteMarkers;
    /// <summary>
    /// 本图敌人类型索引
    /// </summary>
    public readonly int EnemyTypeIndex;
    /// <summary>
    /// 地图诊断名称，不参与战斗规则
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Unity/YooAsset 战斗地图资源地址
    /// </summary>
    public readonly string ResourceAddress;
   
    public const int __ID__ = 2052541190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "gridWidth:" + GridWidth + ","
        + "gridHeight:" + GridHeight + ","
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "mapIndex:" + MapIndex + ","
        + "blocks:" + Blocks + ","
        + "playerPath:" + Luban.StringUtil.CollectionToString(PlayerPath) + ","
        + "opponentPath:" + Luban.StringUtil.CollectionToString(OpponentPath) + ","
        + "cellWidth:" + CellWidth + ","
        + "cellHeight:" + CellHeight + ","
        + "mapCount:" + MapCount + ","
        + "grid:" + Luban.StringUtil.CollectionToString(Grid) + ","
        + "playerEntry:" + PlayerEntry + ","
        + "playerStart:" + PlayerStart + ","
        + "playerEnd:" + PlayerEnd + ","
        + "opponentEntry:" + OpponentEntry + ","
        + "opponentStart:" + OpponentStart + ","
        + "opponentEnd:" + OpponentEnd + ","
        + "routeMarkers:" + Luban.StringUtil.CollectionToString(RouteMarkers) + ","
        + "enemyTypeIndex:" + EnemyTypeIndex + ","
        + "name:" + Name + ","
        + "resourceAddress:" + ResourceAddress + ","
        + "}";
    }
}
}

