
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class Projectile : Luban.BeanBase
{
    public Projectile(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); Types = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Types.Add(_e0);}}
    }

    public static Projectile DeserializeProjectile(ByteBuf _buf)
    {
        return new battle.Projectile(_buf);
    }

    /// <summary>
    /// 弹道类型列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> Types;
   
    public const int __ID__ = -736931585;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "types:" + Luban.StringUtil.CollectionToString(Types) + ","
        + "}";
    }
}
}

