
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 军衔关卡配置
/// </summary>
public sealed partial class Rank : Luban.BeanBase
{
    public Rank(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
    }

    public static Rank DeserializeRank(ByteBuf _buf)
    {
        return new battle.Rank(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = -795583550;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}
}

