
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗结果字段说明
/// </summary>
public sealed partial class ResultSchema : Luban.BeanBase
{
    public ResultSchema(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
    }

    public static ResultSchema DeserializeResultSchema(ByteBuf _buf)
    {
        return new battle.ResultSchema(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = -299124300;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}
}

