
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 技能配置
/// </summary>
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ResName = _buf.ReadString();
        Category = _buf.ReadString();
        if(_buf.ReadBool()){ RangeTiles = _buf.ReadFloat(); } else { RangeTiles = null; }
        if(_buf.ReadBool()){ CooldownSeconds = _buf.ReadInt(); } else { CooldownSeconds = null; }
        HandlerKey = _buf.ReadString();
        if(_buf.ReadBool()){ EffectBuffId = _buf.ReadInt(); } else { EffectBuffId = null; }
        if(_buf.ReadBool()){ EffectDurationMs = _buf.ReadInt(); } else { EffectDurationMs = null; }
        if(_buf.ReadBool()){ TriggerAttackCount = _buf.ReadInt(); } else { TriggerAttackCount = null; }
        if(_buf.ReadBool()){ EffectDamageMultiplier = _buf.ReadFloat(); } else { EffectDamageMultiplier = null; }
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new battle.Skill(_buf);
    }

    /// <summary>
    /// 主键，技能唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名，原主键
    /// </summary>
    public readonly string ResName;
    /// <summary>
    /// 类别，只能填 active / boss / passive
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 作用范围格数，只被特定 Handler 解释
    /// </summary>
    public readonly float? RangeTiles;
    /// <summary>
    /// 冷却秒数，必须填写且不能为负
    /// </summary>
    public readonly int? CooldownSeconds;
    /// <summary>
    /// 代码处理器注册键，不能为空，必须由程序确认已注册
    /// </summary>
    public readonly string HandlerKey;
    /// <summary>
    /// 效果 Buff ID，引用 buff.Id
    /// </summary>
    public readonly int? EffectBuffId;
    /// <summary>
    /// Buff/效果持续毫秒
    /// </summary>
    public readonly int? EffectDurationMs;
    /// <summary>
    /// 累计多少次普通攻击后触发主动技能
    /// </summary>
    public readonly int? TriggerAttackCount;
    /// <summary>
    /// 单箭伤害倍率，如火箭每箭倍率
    /// </summary>
    public readonly float? EffectDamageMultiplier;
   
    public const int __ID__ = 1107930491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "resName:" + ResName + ","
        + "category:" + Category + ","
        + "rangeTiles:" + RangeTiles + ","
        + "cooldownSeconds:" + CooldownSeconds + ","
        + "handlerKey:" + HandlerKey + ","
        + "effectBuffId:" + EffectBuffId + ","
        + "effectDurationMs:" + EffectDurationMs + ","
        + "triggerAttackCount:" + TriggerAttackCount + ","
        + "effectDamageMultiplier:" + EffectDamageMultiplier + ","
        + "}";
    }
}
}

