
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 技能配置
/// </summary>
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Name = _buf.ReadString();
        Category = _buf.ReadString();
        Description = _buf.ReadString();
        if(_buf.ReadBool()){ HealthMultiplier = _buf.ReadInt(); } else { HealthMultiplier = null; }
        if(_buf.ReadBool()){ Speed = _buf.ReadInt(); } else { Speed = null; }
        if(_buf.ReadBool()){ RangeTiles = _buf.ReadFloat(); } else { RangeTiles = null; }
        if(_buf.ReadBool()){ CooldownSeconds = _buf.ReadInt(); } else { CooldownSeconds = null; }
        Source = _buf.ReadString();
        if(_buf.ReadBool()){ Confidence = _buf.ReadString(); } else { Confidence = null; }
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new battle.Skill(_buf);
    }

    /// <summary>
    /// 键(主键)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类别
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 血量倍数
    /// </summary>
    public readonly int? HealthMultiplier;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly int? Speed;
    /// <summary>
    /// 范围(格)
    /// </summary>
    public readonly float? RangeTiles;
    /// <summary>
    /// 冷却(秒)
    /// </summary>
    public readonly int? CooldownSeconds;
    /// <summary>
    /// 源码标记
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 置信度
    /// </summary>
    public readonly string Confidence;
   
    public const int __ID__ = 1107930491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "name:" + Name + ","
        + "category:" + Category + ","
        + "description:" + Description + ","
        + "healthMultiplier:" + HealthMultiplier + ","
        + "speed:" + Speed + ","
        + "rangeTiles:" + RangeTiles + ","
        + "cooldownSeconds:" + CooldownSeconds + ","
        + "source:" + Source + ","
        + "confidence:" + Confidence + ","
        + "}";
    }
}
}

