
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 兵种表现 Profile(美术锚点偏移)
/// </summary>
public sealed partial class SoldierVisual : Luban.BeanBase
{
    public SoldierVisual(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AnimationKey = _buf.ReadString();
        BodyLocalOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        HitEffectPointOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        ProjectileOriginOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        WeaponPivotOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        DefaultFacing = _buf.ReadInt();
        HasWeaponPivot = _buf.ReadBool();
        HasProjectileOrigin = _buf.ReadBool();
    }

    public static SoldierVisual DeserializeSoldierVisual(ByteBuf _buf)
    {
        return new battle.SoldierVisual(_buf);
    }

    public readonly int Id;
    public readonly string AnimationKey;
    public readonly UnityEngine.Vector2 BodyLocalOffset;
    public readonly UnityEngine.Vector2 HitEffectPointOffset;
    public readonly UnityEngine.Vector2 ProjectileOriginOffset;
    public readonly UnityEngine.Vector2 WeaponPivotOffset;
    public readonly int DefaultFacing;
    public readonly bool HasWeaponPivot;
    public readonly bool HasProjectileOrigin;
   
    public const int __ID__ = 1181049996;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "animationKey:" + AnimationKey + ","
        + "bodyLocalOffset:" + BodyLocalOffset + ","
        + "hitEffectPointOffset:" + HitEffectPointOffset + ","
        + "projectileOriginOffset:" + ProjectileOriginOffset + ","
        + "weaponPivotOffset:" + WeaponPivotOffset + ","
        + "defaultFacing:" + DefaultFacing + ","
        + "hasWeaponPivot:" + HasWeaponPivot + ","
        + "hasProjectileOrigin:" + HasProjectileOrigin + ","
        + "}";
    }
}
}

