
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 兵种表现 Profile(美术锚点偏移)
/// </summary>
public sealed partial class SoldierVisual : Luban.BeanBase
{
    public SoldierVisual(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BodyLocalOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        HitEffectPointOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        ProjectileOriginOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        WeaponPivotOffset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        DefaultFacing = _buf.ReadInt();
        HasWeaponPivot = _buf.ReadBool();
        HasProjectileOrigin = _buf.ReadBool();
    }

    public static SoldierVisual DeserializeSoldierVisual(ByteBuf _buf)
    {
        return new battle.SoldierVisual(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Body 偏移，世界单位
    /// </summary>
    public readonly UnityEngine.Vector2 BodyLocalOffset;
    /// <summary>
    /// 受击特效挂点偏移，世界单位
    /// </summary>
    public readonly UnityEngine.Vector2 HitEffectPointOffset;
    /// <summary>
    /// 箭矢出生点偏移，仅弓兵有值
    /// </summary>
    public readonly UnityEngine.Vector2 ProjectileOriginOffset;
    /// <summary>
    /// 武器挂点偏移，仅枪兵有值
    /// </summary>
    public readonly UnityEngine.Vector2 WeaponPivotOffset;
    /// <summary>
    /// 默认朝向：1=右 / -1=左
    /// </summary>
    public readonly int DefaultFacing;
    /// <summary>
    /// 是否有武器挂点，仅枪兵为 true
    /// </summary>
    public readonly bool HasWeaponPivot;
    /// <summary>
    /// 是否有投射物原点，仅弓兵为 true
    /// </summary>
    public readonly bool HasProjectileOrigin;
   
    public const int __ID__ = 1181049996;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bodyLocalOffset:" + BodyLocalOffset + ","
        + "hitEffectPointOffset:" + HitEffectPointOffset + ","
        + "projectileOriginOffset:" + ProjectileOriginOffset + ","
        + "weaponPivotOffset:" + WeaponPivotOffset + ","
        + "defaultFacing:" + DefaultFacing + ","
        + "hasWeaponPivot:" + HasWeaponPivot + ","
        + "hasProjectileOrigin:" + HasProjectileOrigin + ","
        + "}";
    }
}
}

