
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// Buff类型配置
/// </summary>
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, battle.Buff> _dataMap;
    private readonly System.Collections.Generic.List<battle.Buff> _dataList;
    
    public TbBuff(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.Buff>(n);
        _dataList = new System.Collections.Generic.List<battle.Buff>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.Buff _v;
            _v = global::GameConfig.battle.Buff.DeserializeBuff(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.Buff> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.Buff> DataList => _dataList;

    public battle.Buff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.Buff Get(int key) => _dataMap[key];
    public battle.Buff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

