
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 最简牌组配置(task 3.1 新增,spec 6.5 均匀四兵)
/// </summary>
public partial class TbDeck
{
    private readonly System.Collections.Generic.Dictionary<string, battle.Deck> _dataMap;
    private readonly System.Collections.Generic.List<battle.Deck> _dataList;
    
    public TbDeck(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, battle.Deck>(n);
        _dataList = new System.Collections.Generic.List<battle.Deck>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.Deck _v;
            _v = global::GameConfig.battle.Deck.DeserializeDeck(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Mode, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, battle.Deck> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.Deck> DataList => _dataList;

    public battle.Deck GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.Deck Get(string key) => _dataMap[key];
    public battle.Deck this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

