
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗经济配置
/// </summary>
public partial class TbEconomy
{

     private readonly battle.Economy _data;

     public battle.Economy Data => _data;

    public TbEconomy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.battle.Economy.DeserializeEconomy(_buf);
    }


    /// <summary>
    /// 初始金币
    /// </summary>
     public int InitialGold => _data.InitialGold;
    /// <summary>
    /// 刷新起始消耗
    /// </summary>
     public int RefreshCostStart => _data.RefreshCostStart;
    /// <summary>
    /// 刷新递增
    /// </summary>
     public int RefreshCostIncrement => _data.RefreshCostIncrement;
    /// <summary>
    /// 单位基础消耗
    /// </summary>
     public int UnitBaseCost => _data.UnitBaseCost;
    /// <summary>
    /// 手牌数
    /// </summary>
     public int HandSize => _data.HandSize;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

