
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗经济配置
/// </summary>
public partial class TbEconomy
{

     private readonly battle.Economy _data;

     public battle.Economy Data => _data;

    public TbEconomy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.battle.Economy.DeserializeEconomy(_buf);
    }


     public int InitialGold => _data.InitialGold;
     public int RefreshCostStart => _data.RefreshCostStart;
     public int RefreshCostIncrement => _data.RefreshCostIncrement;
     public int UnitBaseCost => _data.UnitBaseCost;
     public int HandSize => _data.HandSize;
    /// <summary>
    /// 玩家方最大生命
    /// </summary>
     public int PlayerMaxHealth => _data.PlayerMaxHealth;
    /// <summary>
    /// 对手方最大生命
    /// </summary>
     public int OpponentMaxHealth => _data.OpponentMaxHealth;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

