
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 敌人运行时数值(公式输入,task 3.1 新增)
/// </summary>
public partial class TbEnemyStats
{
    private readonly System.Collections.Generic.Dictionary<int, battle.EnemyStats> _dataMap;
    private readonly System.Collections.Generic.List<battle.EnemyStats> _dataList;
    
    public TbEnemyStats(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.EnemyStats>(n);
        _dataList = new System.Collections.Generic.List<battle.EnemyStats>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.EnemyStats _v;
            _v = global::GameConfig.battle.EnemyStats.DeserializeEnemyStats(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.EnemyStats> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.EnemyStats> DataList => _dataList;

    public battle.EnemyStats GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.EnemyStats Get(int key) => _dataMap[key];
    public battle.EnemyStats this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

