
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 地图配置
/// </summary>
public partial class TbMap
{

     private readonly battle.Map _data;

     public battle.Map Data => _data;

    public TbMap(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.battle.Map.DeserializeMap(_buf);
    }


    /// <summary>
    /// 网格宽
    /// </summary>
     public int GridWidth => _data.GridWidth;
    /// <summary>
    /// 网格高
    /// </summary>
     public int GridHeight => _data.GridHeight;
    /// <summary>
    /// 宽
    /// </summary>
     public int Width => _data.Width;
    /// <summary>
    /// 高
    /// </summary>
     public int Height => _data.Height;
    /// <summary>
    /// 地图索引
    /// </summary>
     public int MapIndex => _data.MapIndex;
    /// <summary>
    /// 阻挡点
    /// </summary>
     public string Blocks => _data.Blocks;
    /// <summary>
    /// 玩家路径
    /// </summary>
     public System.Collections.Generic.List<UnityEngine.Vector2Int> PlayerPath => _data.PlayerPath;
    /// <summary>
    /// 对手路径
    /// </summary>
     public System.Collections.Generic.List<UnityEngine.Vector2Int> OpponentPath => _data.OpponentPath;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

