
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 对手AI难度配置
/// </summary>
public partial class TbOpponentAiDifficulty
{
    private readonly System.Collections.Generic.Dictionary<int, battle.OpponentAiDifficulty> _dataMap;
    private readonly System.Collections.Generic.List<battle.OpponentAiDifficulty> _dataList;
    
    public TbOpponentAiDifficulty(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.OpponentAiDifficulty>(n);
        _dataList = new System.Collections.Generic.List<battle.OpponentAiDifficulty>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.OpponentAiDifficulty _v;
            _v = global::GameConfig.battle.OpponentAiDifficulty.DeserializeOpponentAiDifficulty(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.OpponentAiDifficulty> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.OpponentAiDifficulty> DataList => _dataList;

    public battle.OpponentAiDifficulty GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.OpponentAiDifficulty Get(int key) => _dataMap[key];
    public battle.OpponentAiDifficulty this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

