
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 弹道类型
/// </summary>
public partial class TbProjectile
{

     private readonly battle.Projectile _data;

     public battle.Projectile Data => _data;

    public TbProjectile(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.battle.Projectile.DeserializeProjectile(_buf);
    }


     public int Id => _data.Id;
     public System.Collections.Generic.List<string> Types => _data.Types;
    /// <summary>
    /// 本期唯一注册投射物类型(SimpleDynamicArrow)
    /// </summary>
     public string PrimaryType => _data.PrimaryType;
    /// <summary>
    /// 箭矢移动速度(px/s,TargetEnemyMovement 默认 200)
    /// </summary>
     public int ArrowSpeed => _data.ArrowSpeed;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

