
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 军衔关卡配置
/// </summary>
public partial class TbRank
{
    private readonly System.Collections.Generic.Dictionary<int, battle.Rank> _dataMap;
    private readonly System.Collections.Generic.List<battle.Rank> _dataList;
    
    public TbRank(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.Rank>(n);
        _dataList = new System.Collections.Generic.List<battle.Rank>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.Rank _v;
            _v = global::GameConfig.battle.Rank.DeserializeRank(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.Rank> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.Rank> DataList => _dataList;

    public battle.Rank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.Rank Get(int key) => _dataMap[key];
    public battle.Rank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

