
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 兵种表现 Profile(美术锚点偏移)
/// </summary>
public partial class TbSoldierVisual
{
    private readonly System.Collections.Generic.Dictionary<int, battle.SoldierVisual> _dataMap;
    private readonly System.Collections.Generic.List<battle.SoldierVisual> _dataList;
    
    public TbSoldierVisual(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.SoldierVisual>(n);
        _dataList = new System.Collections.Generic.List<battle.SoldierVisual>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.SoldierVisual _v;
            _v = global::GameConfig.battle.SoldierVisual.DeserializeSoldierVisual(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.SoldierVisual> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.SoldierVisual> DataList => _dataList;

    public battle.SoldierVisual GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.SoldierVisual Get(int key) => _dataMap[key];
    public battle.SoldierVisual this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

