
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 小兵等级倍数
/// </summary>
public partial class TbUnitLevel
{
    private readonly System.Collections.Generic.Dictionary<int, battle.UnitLevel> _dataMap;
    private readonly System.Collections.Generic.List<battle.UnitLevel> _dataList;
    
    public TbUnitLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.UnitLevel>(n);
        _dataList = new System.Collections.Generic.List<battle.UnitLevel>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.UnitLevel _v;
            _v = global::GameConfig.battle.UnitLevel.DeserializeUnitLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.UnitLevel> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.UnitLevel> DataList => _dataList;

    public battle.UnitLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.UnitLevel Get(int key) => _dataMap[key];
    public battle.UnitLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

