
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 小兵基础配置
/// </summary>
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<int, battle.Unit> _dataMap;
    private readonly System.Collections.Generic.List<battle.Unit> _dataList;
    
    public TbUnit(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.Unit>(n);
        _dataList = new System.Collections.Generic.List<battle.Unit>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.Unit _v;
            _v = global::GameConfig.battle.Unit.DeserializeUnit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.Unit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.Unit> DataList => _dataList;

    public battle.Unit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.Unit Get(int key) => _dataMap[key];
    public battle.Unit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

