
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 小兵等级倍数
/// </summary>
public partial class TbUnitLevel
{

     private readonly battle.UnitLevel _data;

     public battle.UnitLevel Data => _data;

    public TbUnitLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.battle.UnitLevel.DeserializeUnitLevel(_buf);
    }


    /// <summary>
    /// 最大等级
    /// </summary>
     public int MaxLevel => _data.MaxLevel;
    /// <summary>
    /// 伤害等级倍数
    /// </summary>
     public System.Collections.Generic.List<float> DamageLevelMultipliers => _data.DamageLevelMultipliers;
    /// <summary>
    /// 攻速等级倍数
    /// </summary>
     public System.Collections.Generic.List<float> AttackSpeedLevelMultipliers => _data.AttackSpeedLevelMultipliers;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

