
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 波次配置
/// </summary>
public partial class TbWave
{

     private readonly battle.Wave _data;

     public battle.Wave Data => _data;

    public TbWave(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.battle.Wave.DeserializeWave(_buf);
    }


    /// <summary>
    /// 【deprecated】旧字段，不再驱动有限波次
    /// </summary>
     public System.Collections.Generic.List<int> WaveUnitCounts => _data.WaveUnitCounts;
    /// <summary>
    /// 【deprecated】旧字段，不再驱动有限波次
    /// </summary>
     public System.Collections.Generic.List<int> BossWaveNumbers => _data.BossWaveNumbers;
    /// <summary>
    /// 【deprecated】旧字段，不再驱动有限波次
    /// </summary>
     public System.Collections.Generic.List<float> BossSpawnChances => _data.BossSpawnChances;
    /// <summary>
    /// 【deprecated】旧字段，不再驱动有限波次
    /// </summary>
     public System.Collections.Generic.List<int> SpawnStrategyWeights => _data.SpawnStrategyWeights;
    /// <summary>
    /// 生成策略表，仅由逐波 strategyProfile 显式引用
    /// </summary>
     public System.Collections.Generic.List<System.Collections.Generic.List<float>> SpawnStrategies => _data.SpawnStrategies;
    /// <summary>
    /// 【deprecated】旧字段，不再驱动有限波次
    /// </summary>
     public bool SkipBoss => _data.SkipBoss;
    /// <summary>
    /// 当前生效的波次计划ID
    /// </summary>
     public string ActivePlanId => _data.ActivePlanId;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

