
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 波次计划表
/// </summary>
public partial class TbWavePlan
{
    private readonly System.Collections.Generic.List<battle.WavePlan> _dataList;


    public TbWavePlan(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<battle.WavePlan>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.WavePlan _v;
            _v = global::GameConfig.battle.WavePlan.DeserializeWavePlan(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<battle.WavePlan> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

