
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器配置(原始)
/// </summary>
public partial class TbWeapon
{
    private readonly System.Collections.Generic.Dictionary<int, battle.Weapon> _dataMap;
    private readonly System.Collections.Generic.List<battle.Weapon> _dataList;
    
    public TbWeapon(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.Weapon>(n);
        _dataList = new System.Collections.Generic.List<battle.Weapon>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.Weapon _v;
            _v = global::GameConfig.battle.Weapon.DeserializeWeapon(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.Weapon> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.Weapon> DataList => _dataList;

    public battle.Weapon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.Weapon Get(int key) => _dataMap[key];
    public battle.Weapon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

