
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器符号注册表(逆向快照)
/// </summary>
public partial class TbWeaponRegistry
{
    private readonly System.Collections.Generic.Dictionary<string, battle.WeaponRegistry> _dataMap;
    private readonly System.Collections.Generic.List<battle.WeaponRegistry> _dataList;
    
    public TbWeaponRegistry(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, battle.WeaponRegistry>(n);
        _dataList = new System.Collections.Generic.List<battle.WeaponRegistry>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.WeaponRegistry _v;
            _v = global::GameConfig.battle.WeaponRegistry.DeserializeWeaponRegistry(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Symbol, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, battle.WeaponRegistry> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.WeaponRegistry> DataList => _dataList;

    public battle.WeaponRegistry GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.WeaponRegistry Get(string key) => _dataMap[key];
    public battle.WeaponRegistry this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

