
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器碎片战斗结算奖励候选
/// </summary>
public partial class TbWeaponReward
{
    private readonly System.Collections.Generic.Dictionary<int, battle.WeaponReward> _dataMap;
    private readonly System.Collections.Generic.List<battle.WeaponReward> _dataList;
    
    public TbWeaponReward(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.WeaponReward>(n);
        _dataList = new System.Collections.Generic.List<battle.WeaponReward>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.WeaponReward _v;
            _v = global::GameConfig.battle.WeaponReward.DeserializeWeaponReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.WeaponReward> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.WeaponReward> DataList => _dataList;

    public battle.WeaponReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.WeaponReward Get(int key) => _dataMap[key];
    public battle.WeaponReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

