
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器名字拆字
/// </summary>
public partial class TbWeaponText
{
    private readonly System.Collections.Generic.Dictionary<int, battle.WeaponText> _dataMap;
    private readonly System.Collections.Generic.List<battle.WeaponText> _dataList;
    
    public TbWeaponText(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.WeaponText>(n);
        _dataList = new System.Collections.Generic.List<battle.WeaponText>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.WeaponText _v;
            _v = global::GameConfig.battle.WeaponText.DeserializeWeaponText(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.WeaponText> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.WeaponText> DataList => _dataList;

    public battle.WeaponText GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.WeaponText Get(int key) => _dataMap[key];
    public battle.WeaponText this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

