
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class Unit : Luban.BeanBase
{
    public Unit(ByteBuf _buf) 
    {
        Index = _buf.ReadInt();
        Text = _buf.ReadString();
        AnimationKey = _buf.ReadString();
        RangeCells = _buf.ReadFloat();
        AttackDamage = _buf.ReadInt();
        AttackIntervalSeconds = _buf.ReadFloat();
        DamageMode = _buf.ReadString();
        TargetPolicy = _buf.ReadString();
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new battle.Unit(_buf);
    }

    /// <summary>
    /// 索引
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Text;
    /// <summary>
    /// 动画键
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// 攻击距离(格)
    /// </summary>
    public readonly float RangeCells;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int AttackDamage;
    /// <summary>
    /// 攻击间隔(秒)
    /// </summary>
    public readonly float AttackIntervalSeconds;
    /// <summary>
    /// 伤害模式
    /// </summary>
    public readonly string DamageMode;
    /// <summary>
    /// 目标策略
    /// </summary>
    public readonly string TargetPolicy;
   
    public const int __ID__ = -795481830;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "text:" + Text + ","
        + "animationKey:" + AnimationKey + ","
        + "rangeCells:" + RangeCells + ","
        + "attackDamage:" + AttackDamage + ","
        + "attackIntervalSeconds:" + AttackIntervalSeconds + ","
        + "damageMode:" + DamageMode + ","
        + "targetPolicy:" + TargetPolicy + ","
        + "}";
    }
}
}

