
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 小兵基础配置
/// </summary>
public sealed partial class Unit : Luban.BeanBase
{
    public Unit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Text = _buf.ReadString();
        AnimationKey = _buf.ReadString();
        RangeCells = _buf.ReadFloat();
        AttackDamage = _buf.ReadInt();
        AttackIntervalSeconds = _buf.ReadFloat();
        DamageMode = _buf.ReadString();
        TargetPolicy = _buf.ReadString();
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new battle.Unit(_buf);
    }

    /// <summary>
    /// 主键，兵种唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Text;
    /// <summary>
    /// 动画键，关联 soldier_visual 表取得锚点偏移（knife/bow/pike/cavalry）
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// 攻击范围，以格为单位
    /// </summary>
    public readonly float RangeCells;
    /// <summary>
    /// 基础攻击力
    /// </summary>
    public readonly int AttackDamage;
    /// <summary>
    /// 攻击间隔，秒
    /// </summary>
    public readonly float AttackIntervalSeconds;
    /// <summary>
    /// 伤害模式：近战/单体/近战枪击/范围
    /// </summary>
    public readonly string DamageMode;
    /// <summary>
    /// 选敌策略：nearest（最近）/ closest_end（离终点最近）
    /// </summary>
    public readonly string TargetPolicy;
   
    public const int __ID__ = -795481830;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "text:" + Text + ","
        + "animationKey:" + AnimationKey + ","
        + "rangeCells:" + RangeCells + ","
        + "attackDamage:" + AttackDamage + ","
        + "attackIntervalSeconds:" + AttackIntervalSeconds + ","
        + "damageMode:" + DamageMode + ","
        + "targetPolicy:" + TargetPolicy + ","
        + "}";
    }
}
}

