
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 小兵基础配置
/// </summary>
public sealed partial class Unit : Luban.BeanBase
{
    public Unit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Text = _buf.ReadString();
        AnimationKey = _buf.ReadString();
        RangeCells = _buf.ReadFloat();
        AttackDamage = _buf.ReadInt();
        AttackIntervalSeconds = _buf.ReadFloat();
        DamageMode = _buf.ReadString();
        TargetPolicy = _buf.ReadString();
        if(_buf.ReadBool()){ Status = _buf.ReadString(); } else { Status = null; }
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new battle.Unit(_buf);
    }

    public readonly int Id;
    public readonly string Text;
    public readonly string AnimationKey;
    public readonly float RangeCells;
    public readonly int AttackDamage;
    public readonly float AttackIntervalSeconds;
    public readonly string DamageMode;
    public readonly string TargetPolicy;
    /// <summary>
    /// 状态标注(CORE_COMPLETE)
    /// </summary>
    public readonly string Status;
   
    public const int __ID__ = -795481830;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "text:" + Text + ","
        + "animationKey:" + AnimationKey + ","
        + "rangeCells:" + RangeCells + ","
        + "attackDamage:" + AttackDamage + ","
        + "attackIntervalSeconds:" + AttackIntervalSeconds + ","
        + "damageMode:" + DamageMode + ","
        + "targetPolicy:" + TargetPolicy + ","
        + "status:" + Status + ","
        + "}";
    }
}
}

