
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 小兵等级倍数
/// </summary>
public sealed partial class UnitLevel : Luban.BeanBase
{
    public UnitLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DamageLevelMultipliers = _buf.ReadFloat();
        AttackSpeedLevelMultipliers = _buf.ReadFloat();
    }

    public static UnitLevel DeserializeUnitLevel(ByteBuf _buf)
    {
        return new battle.UnitLevel(_buf);
    }

    /// <summary>
    /// 等级 ID（主键），从 1 开始
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 该等级的伤害倍率，乘到基础攻击力上
    /// </summary>
    public readonly float DamageLevelMultipliers;
    /// <summary>
    /// 该等级的攻速倍率，乘到基础攻速上
    /// </summary>
    public readonly float AttackSpeedLevelMultipliers;
   
    public const int __ID__ = 242246282;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "damageLevelMultipliers:" + DamageLevelMultipliers + ","
        + "attackSpeedLevelMultipliers:" + AttackSpeedLevelMultipliers + ","
        + "}";
    }
}
}

