
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class UnitLevel : Luban.BeanBase
{
    public UnitLevel(ByteBuf _buf) 
    {
        MaxLevel = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); DamageLevelMultipliers = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); DamageLevelMultipliers.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AttackSpeedLevelMultipliers = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); AttackSpeedLevelMultipliers.Add(_e0);}}
    }

    public static UnitLevel DeserializeUnitLevel(ByteBuf _buf)
    {
        return new battle.UnitLevel(_buf);
    }

    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 伤害等级倍数
    /// </summary>
    public readonly System.Collections.Generic.List<float> DamageLevelMultipliers;
    /// <summary>
    /// 攻速等级倍数
    /// </summary>
    public readonly System.Collections.Generic.List<float> AttackSpeedLevelMultipliers;
   
    public const int __ID__ = 242246282;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "maxLevel:" + MaxLevel + ","
        + "damageLevelMultipliers:" + Luban.StringUtil.CollectionToString(DamageLevelMultipliers) + ","
        + "attackSpeedLevelMultipliers:" + Luban.StringUtil.CollectionToString(AttackSpeedLevelMultipliers) + ","
        + "}";
    }
}
}

