
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 波次配置
/// </summary>
public sealed partial class Wave : Luban.BeanBase
{
    public Wave(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ActivePlanId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); WaveUnitCounts = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); WaveUnitCounts.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BossWaveNumbers = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BossWaveNumbers.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BossSpawnChances = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); BossSpawnChances.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SpawnStrategyWeights = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SpawnStrategyWeights.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SpawnStrategies = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<float> _e0;  {int n1 = _buf.ReadSize(); _e0 = new System.Collections.Generic.List<float>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { float _e1;  _e1 = _buf.ReadFloat(); _e0.Add(_e1);}} SpawnStrategies.Add(_e0);}}
    }

    public static Wave DeserializeWave(ByteBuf _buf)
    {
        return new battle.Wave(_buf);
    }

    /// <summary>
    /// 占位
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 当前启用的波次计划 ID，必须能在 wave_plan.Id 中找到
    /// </summary>
    public readonly int ActivePlanId;
    /// <summary>
    /// 已废弃，不再决定波次内容
    /// </summary>
    public readonly System.Collections.Generic.List<int> WaveUnitCounts;
    /// <summary>
    /// 已废弃
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossWaveNumbers;
    /// <summary>
    /// 已废弃
    /// </summary>
    public readonly System.Collections.Generic.List<float> BossSpawnChances;
    /// <summary>
    /// 已废弃
    /// </summary>
    public readonly System.Collections.Generic.List<int> SpawnStrategyWeights;
    /// <summary>
    /// 生成策略权重二维表，wave_plan.strategyProfile 是这里的行索引（从 0 起）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> SpawnStrategies;
   
    public const int __ID__ = -795434353;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "activePlanId:" + ActivePlanId + ","
        + "waveUnitCounts:" + Luban.StringUtil.CollectionToString(WaveUnitCounts) + ","
        + "bossWaveNumbers:" + Luban.StringUtil.CollectionToString(BossWaveNumbers) + ","
        + "bossSpawnChances:" + Luban.StringUtil.CollectionToString(BossSpawnChances) + ","
        + "spawnStrategyWeights:" + Luban.StringUtil.CollectionToString(SpawnStrategyWeights) + ","
        + "spawnStrategies:" + Luban.StringUtil.CollectionToString(SpawnStrategies) + ","
        + "}";
    }
}
}

