
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 波次配置
/// </summary>
public sealed partial class Wave : Luban.BeanBase
{
    public Wave(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); WaveUnitCounts = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); WaveUnitCounts.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BossWaveNumbers = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BossWaveNumbers.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BossSpawnChances = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); BossSpawnChances.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SpawnStrategyWeights = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SpawnStrategyWeights.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SpawnStrategies = new System.Collections.Generic.List<System.Collections.Generic.List<float>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<float> _e0;  {int n1 = _buf.ReadSize(); _e0 = new System.Collections.Generic.List<float>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { float _e1;  _e1 = _buf.ReadFloat(); _e0.Add(_e1);}} SpawnStrategies.Add(_e0);}}
        SkipBoss = _buf.ReadBool();
    }

    public static Wave DeserializeWave(ByteBuf _buf)
    {
        return new battle.Wave(_buf);
    }

    public readonly System.Collections.Generic.List<int> WaveUnitCounts;
    public readonly System.Collections.Generic.List<int> BossWaveNumbers;
    public readonly System.Collections.Generic.List<float> BossSpawnChances;
    public readonly System.Collections.Generic.List<int> SpawnStrategyWeights;
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<float>> SpawnStrategies;
    /// <summary>
    /// 本期显式跳过 Boss
    /// </summary>
    public readonly bool SkipBoss;
   
    public const int __ID__ = -795434353;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "waveUnitCounts:" + Luban.StringUtil.CollectionToString(WaveUnitCounts) + ","
        + "bossWaveNumbers:" + Luban.StringUtil.CollectionToString(BossWaveNumbers) + ","
        + "bossSpawnChances:" + Luban.StringUtil.CollectionToString(BossSpawnChances) + ","
        + "spawnStrategyWeights:" + Luban.StringUtil.CollectionToString(SpawnStrategyWeights) + ","
        + "spawnStrategies:" + Luban.StringUtil.CollectionToString(SpawnStrategies) + ","
        + "skipBoss:" + SkipBoss + ","
        + "}";
    }
}
}

