
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 波次计划表
/// </summary>
public sealed partial class WavePlan : Luban.BeanBase
{
    public WavePlan(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Order = _buf.ReadInt();
        Kind = (battle.EWaveKind)_buf.ReadInt();
        if(_buf.ReadBool()){ EnemyId = _buf.ReadInt(); } else { EnemyId = null; }
        NormalCount = _buf.ReadInt();
        DifficultyIndex = _buf.ReadInt();
        if(_buf.ReadBool()){ BossId = _buf.ReadInt(); } else { BossId = null; }
        PreDelayMs = _buf.ReadLong();
        SpawnIntervalMs = _buf.ReadLong();
        PostDelayMs = _buf.ReadLong();
        PlayerLane = _buf.ReadBool();
        OpponentLane = _buf.ReadBool();
        StrategyProfile = _buf.ReadInt();
    }

    public static WavePlan DeserializeWavePlan(ByteBuf _buf)
    {
        return new battle.WavePlan(_buf);
    }

    /// <summary>
    /// 计划 ID，应与 wave.activePlanId 一致
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 波次顺序，从 1 开始连续递增，不可重复、不可跳号
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 波次类型：Normal=普通波 / Boss=Boss 波
    /// </summary>
    public readonly battle.EWaveKind Kind;
    /// <summary>
    /// Normal 波的敌人 ID，留空时使用地图的 EnemyId
    /// </summary>
    public readonly int? EnemyId;
    /// <summary>
    /// Normal 波怪物数量，Boss 波填 0
    /// </summary>
    public readonly int NormalCount;
    /// <summary>
    /// 难度索引，索引 enemystats.healthByWave，从 0 开始
    /// </summary>
    public readonly int DifficultyIndex;
    /// <summary>
    /// Boss 波必填的 Boss ID，Normal 波留空
    /// </summary>
    public readonly int? BossId;
    /// <summary>
    /// 本波开始前的等待时间，毫秒
    /// </summary>
    public readonly long PreDelayMs;
    /// <summary>
    /// 普通怪之间的出生间隔，毫秒
    /// </summary>
    public readonly long SpawnIntervalMs;
    /// <summary>
    /// 本波结束后的等待时间，毫秒
    /// </summary>
    public readonly long PostDelayMs;
    /// <summary>
    /// 玩家侧是否生成
    /// </summary>
    public readonly bool PlayerLane;
    /// <summary>
    /// 对手侧是否生成，至少一侧必须为 true
    /// </summary>
    public readonly bool OpponentLane;
    /// <summary>
    /// 生成策略索引，引用 wave.spawnStrategies 的行，从 0 开始
    /// </summary>
    public readonly int StrategyProfile;
   
    public const int __ID__ = -2005220776;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "order:" + Order + ","
        + "kind:" + Kind + ","
        + "enemyId:" + EnemyId + ","
        + "normalCount:" + NormalCount + ","
        + "difficultyIndex:" + DifficultyIndex + ","
        + "bossId:" + BossId + ","
        + "preDelayMs:" + PreDelayMs + ","
        + "spawnIntervalMs:" + SpawnIntervalMs + ","
        + "postDelayMs:" + PostDelayMs + ","
        + "playerLane:" + PlayerLane + ","
        + "opponentLane:" + OpponentLane + ","
        + "strategyProfile:" + StrategyProfile + ","
        + "}";
    }
}
}

