
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 波次计划表
/// </summary>
public sealed partial class WavePlan : Luban.BeanBase
{
    public WavePlan(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Order = _buf.ReadInt();
        Kind = (battle.EWaveKind)_buf.ReadInt();
        if(_buf.ReadBool()){ EnemyId = _buf.ReadInt(); } else { EnemyId = null; }
        NormalCount = _buf.ReadInt();
        DifficultyIndex = _buf.ReadInt();
        if(_buf.ReadBool()){ BossId = _buf.ReadInt(); } else { BossId = null; }
        PreDelayMs = _buf.ReadLong();
        SpawnIntervalMs = _buf.ReadLong();
        PostDelayMs = _buf.ReadLong();
        PlayerLane = _buf.ReadBool();
        OpponentLane = _buf.ReadBool();
        StrategyProfile = _buf.ReadInt();
    }

    public static WavePlan DeserializeWavePlan(ByteBuf _buf)
    {
        return new battle.WavePlan(_buf);
    }

    /// <summary>
    /// 计划ID(联合主键1，供 wave.activePlanId 选择)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 波次顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 波次类型
    /// </summary>
    public readonly battle.EWaveKind Kind;
    /// <summary>
    /// 普通敌人Key
    /// </summary>
    public readonly int? EnemyId;
    /// <summary>
    /// 普通敌人数量
    /// </summary>
    public readonly int NormalCount;
    /// <summary>
    /// 难度索引
    /// </summary>
    public readonly int DifficultyIndex;
    /// <summary>
    /// Boss敌人Key
    /// </summary>
    public readonly int? BossId;
    /// <summary>
    /// 前置延迟(毫秒)
    /// </summary>
    public readonly long PreDelayMs;
    /// <summary>
    /// 刷怪间隔(毫秒)
    /// </summary>
    public readonly long SpawnIntervalMs;
    /// <summary>
    /// 后置延迟(毫秒)
    /// </summary>
    public readonly long PostDelayMs;
    /// <summary>
    /// 玩家侧是否出怪
    /// </summary>
    public readonly bool PlayerLane;
    /// <summary>
    /// 对手侧是否出怪
    /// </summary>
    public readonly bool OpponentLane;
    /// <summary>
    /// 逐波策略配置
    /// </summary>
    public readonly int StrategyProfile;
   
    public const int __ID__ = -2005220776;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "order:" + Order + ","
        + "kind:" + Kind + ","
        + "enemyId:" + EnemyId + ","
        + "normalCount:" + NormalCount + ","
        + "difficultyIndex:" + DifficultyIndex + ","
        + "bossId:" + BossId + ","
        + "preDelayMs:" + PreDelayMs + ","
        + "spawnIntervalMs:" + SpawnIntervalMs + ","
        + "postDelayMs:" + PostDelayMs + ","
        + "playerLane:" + PlayerLane + ","
        + "opponentLane:" + OpponentLane + ","
        + "strategyProfile:" + StrategyProfile + ","
        + "}";
    }
}
}

