
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器配置(原始)
/// </summary>
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        AddAttPower = _buf.ReadInt();
        Enabled = _buf.ReadBool();
        HandlerKey = _buf.ReadString();
        Rarity = _buf.ReadInt();
        FragmentNum = _buf.ReadInt();
        Obtainable = _buf.ReadBool();
        DisplayName = _buf.ReadString();
        Description = _buf.ReadString();
        IconLocation = _buf.ReadString();
        Recyclable = _buf.ReadBool();
        RecycleGoldPerFragment = _buf.ReadInt();
    }

    public static Weapon DeserializeWeapon(ByteBuf _buf)
    {
        return new battle.Weapon(_buf);
    }

    /// <summary>
    /// 主键，武器唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 武器类型：0弓/1枪/2刀/3剑
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 增加攻击力
    /// </summary>
    public readonly int AddAttPower;
    /// <summary>
    /// 是否正式接入基础武器框架
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// 武器处理器键，启用武器必填，当前基础武器为 Basic
    /// </summary>
    public readonly string HandlerKey;
    /// <summary>
    /// 品级：0白/1绿/2蓝/3紫/4橙
    /// </summary>
    public readonly int Rarity;
    /// <summary>
    /// 合成一件完整武器所需累计碎片
    /// </summary>
    public readonly int FragmentNum;
    /// <summary>
    /// 是否进入武器奖励候选池
    /// </summary>
    public readonly bool Obtainable;
    /// <summary>
    /// 展示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 武器说明
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 图标资源地址，空表示使用占位图
    /// </summary>
    public readonly string IconLocation;
    /// <summary>
    /// 是否允许回收
    /// </summary>
    public readonly bool Recyclable;
    /// <summary>
    /// 每个碎片的回收金币
    /// </summary>
    public readonly int RecycleGoldPerFragment;
   
    public const int __ID__ = 94848050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "addAttPower:" + AddAttPower + ","
        + "enabled:" + Enabled + ","
        + "handlerKey:" + HandlerKey + ","
        + "rarity:" + Rarity + ","
        + "fragmentNum:" + FragmentNum + ","
        + "obtainable:" + Obtainable + ","
        + "displayName:" + DisplayName + ","
        + "description:" + Description + ","
        + "iconLocation:" + IconLocation + ","
        + "recyclable:" + Recyclable + ","
        + "recycleGoldPerFragment:" + RecycleGoldPerFragment + ","
        + "}";
    }
}
}

