
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器碎片战斗结算奖励候选
/// </summary>
public sealed partial class WeaponReward : Luban.BeanBase
{
    public WeaponReward(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MapId = _buf.ReadInt();
        WeaponId = _buf.ReadInt();
        WinOnly = _buf.ReadBool();
        Weight = _buf.ReadInt();
        MinFragments = _buf.ReadInt();
        MaxFragments = _buf.ReadInt();
    }

    public static WeaponReward DeserializeWeaponReward(ByteBuf _buf)
    {
        return new battle.WeaponReward(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 当前工程零基地图 ID
    /// </summary>
    public readonly int MapId;
    /// <summary>
    /// 武器 ID，引用 TbWeapon.id
    /// </summary>
    public readonly int WeaponId;
    /// <summary>
    /// 是否仅胜利生效
    /// </summary>
    public readonly bool WinOnly;
    /// <summary>
    /// 正整数权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 最小碎片数
    /// </summary>
    public readonly int MinFragments;
    /// <summary>
    /// 最大碎片数
    /// </summary>
    public readonly int MaxFragments;
   
    public const int __ID__ = -87027199;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mapId:" + MapId + ","
        + "weaponId:" + WeaponId + ","
        + "winOnly:" + WinOnly + ","
        + "weight:" + Weight + ","
        + "minFragments:" + MinFragments + ","
        + "maxFragments:" + MaxFragments + ","
        + "}";
    }
}
}

