
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器配置(原始)
/// </summary>
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Txt = _buf.ReadString();
        Rarity = _buf.ReadInt();
        if(_buf.ReadBool()){ RareTxt = _buf.ReadString(); } else { RareTxt = null; }
        AddAttPower = _buf.ReadInt();
        if(_buf.ReadBool()){ Exclusive = _buf.ReadString(); } else { Exclusive = null; }
        Scale = _buf.ReadFloat();
        AnchorY = _buf.ReadFloat();
        Intro = _buf.ReadString();
        FragmentNum = _buf.ReadInt();
        Enabled = _buf.ReadBool();
        HandlerKey = _buf.ReadString();
    }

    public static Weapon DeserializeWeapon(ByteBuf _buf)
    {
        return new battle.Weapon(_buf);
    }

    /// <summary>
    /// ID(主键)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Txt;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly int Rarity;
    /// <summary>
    /// 稀有字
    /// </summary>
    public readonly string RareTxt;
    /// <summary>
    /// 附加攻击力
    /// </summary>
    public readonly int AddAttPower;
    /// <summary>
    /// 专属
    /// </summary>
    public readonly string Exclusive;
    /// <summary>
    /// 缩放
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 锚点Y
    /// </summary>
    public readonly float AnchorY;
    /// <summary>
    /// 简介
    /// </summary>
    public readonly string Intro;
    /// <summary>
    /// 碎片数
    /// </summary>
    public readonly int FragmentNum;
    /// <summary>
    /// 是否接入基础武器框架
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// 武器处理器键(禁用行可空)
    /// </summary>
    public readonly string HandlerKey;
   
    public const int __ID__ = 94848050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "txt:" + Txt + ","
        + "rarity:" + Rarity + ","
        + "rareTxt:" + RareTxt + ","
        + "addAttPower:" + AddAttPower + ","
        + "exclusive:" + Exclusive + ","
        + "scale:" + Scale + ","
        + "anchorY:" + AnchorY + ","
        + "intro:" + Intro + ","
        + "fragmentNum:" + FragmentNum + ","
        + "enabled:" + Enabled + ","
        + "handlerKey:" + HandlerKey + ","
        + "}";
    }
}
}

