
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器配置(原始)
/// </summary>
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        AddAttPower = _buf.ReadInt();
        Enabled = _buf.ReadBool();
        HandlerKey = _buf.ReadString();
    }

    public static Weapon DeserializeWeapon(ByteBuf _buf)
    {
        return new battle.Weapon(_buf);
    }

    /// <summary>
    /// 主键，武器唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 武器类型：0弓/1枪/2刀/3剑
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 增加攻击力
    /// </summary>
    public readonly int AddAttPower;
    /// <summary>
    /// 是否正式接入基础武器框架
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// 武器处理器键，启用武器必填，当前基础武器为 Basic
    /// </summary>
    public readonly string HandlerKey;
   
    public const int __ID__ = 94848050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "addAttPower:" + AddAttPower + ","
        + "enabled:" + Enabled + ","
        + "handlerKey:" + HandlerKey + ","
        + "}";
    }
}
}

