
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 武器名字拆字
/// </summary>
public sealed partial class WeaponText : Luban.BeanBase
{
    public WeaponText(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Txt = _buf.ReadString();
        Quality = _buf.ReadInt();
    }

    public static WeaponText DeserializeWeaponText(ByteBuf _buf)
    {
        return new battle.WeaponText(_buf);
    }

    /// <summary>
    /// ID(主键)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单字
    /// </summary>
    public readonly string Txt;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
   
    public const int __ID__ = -1689414529;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "txt:" + Txt + ","
        + "quality:" + Quality + ","
        + "}";
    }
}
}

