'use strict';
const { EnemyBase,EnemyRuntimeState }=require('../entities/EnemyBase');
const { getSkillDefinition }=require('../skills/SkillDefinitions');
class BossBase extends EnemyBase {
 constructor(definition){super();if(!definition)throw new TypeError('BossBase requires a definition');this.definition=definition;this.typeKey=definition.key;this.typeIndex=definition.typeIndex;this.isBoss=true;this.isSpecial=true;this.visualPoolKey='boss';this.resourcePath=definition.resourcePath||definition.animationKey;this.attackAnimation=definition.attackAnimation;this.idleAnimation=definition.idleAnimation;this.skillKey=definition.skillKey;this.skillRange=0;this.skillCooldownMs=0;this.skillElapsedMs=0;this.skill=null;this.preSkillState=EnemyRuntimeState.MOVING;this.skillTimeline=null;}
 configure(options={}){super.configure(options);this.skillManager=options.skillManager||this.skillManager||null;return this;}
 init(playerLane){this.visual=this.objectPool.takeByKey(this.visualPoolKey,this);this.enemy=this.visual;super.init(playerLane);const stats=this.gameData.resolveBossStats?this.gameData.resolveBossStats(this.typeIndex,{mapEnemyTypeIndex:this.gameData.map.enemyTypeIndex,gridWidth:this.gameData.map.gridWidth}):this._fallbackStats();this.maxHealthBase=stats.ph;this.health=stats.ph;this.baseMoveSpeed=stats.speed;this.skillRange=stats.Lh;this.skillCooldownMs=stats.mh;this.healthText.text=this.health.toFixed(0);this.healthBarBackground.visible=true;this.animation=this.visual.getChildByName('sp');if(!this.animation){this.animation=this.presentation.createAnimation(this,this.resourcePath,true);this.animation.name='sp';this.visual.addChild(this.animation);}if(this.animation&&typeof this.animation.play==='function')this.animation.play(this.idleAnimation||'animation',true);if(this.animation&&typeof this.animation.pos==='function')this.animation.pos(this.visual.width/2,this.visual.height);this.getPath();this.visual.visible=false;const generation=this._lifecycleGeneration;this.presentation.playSpawn(this,()=>{if(generation!==this._lifecycleGeneration||this.inPool)return;this.changeState(EnemyRuntimeState.MOVING);});this.skillElapsedMs=0;if(this.skillManager)this.skill=this.skillManager.attach(this,this.skillKey);return this;}
 _fallbackStats(){const d=getSkillDefinition(this.skillKey);const normal=this.gameData.resolveEnemyStats(this.gameData.map.enemyTypeIndex,this.isPlayerLane);return{ph:normal.ph*(d.healthMultiplier||10),speed:d.speed||10,Lh:(d.rangeTiles||0)*this.gameData.map.gridWidth,mh:(d.cooldownSeconds||10)*1000};}
 update(deltaMs){super.update(deltaMs);if(this.currentState===EnemyRuntimeState.DEAD||this.currentState===EnemyRuntimeState.STUNNED||this.currentState===EnemyRuntimeState.SKILL)return;this.skillElapsedMs+=deltaMs;if(this.skill&&this.skillElapsedMs>=this.skillCooldownMs){this.skillElapsedMs=0;this.activateSkill();}}
 activateSkill(){if(!this.skill||!this.skillManager)return{activated:false,reason:'no-skill'};this.preSkillState=this.currentState===EnemyRuntimeState.SPAWNING?EnemyRuntimeState.MOVING:this.currentState;this.changeState(EnemyRuntimeState.SKILL);const result=this.skillManager.activateBossSkill(this,this.skill,this.buildSkillContext(),{...(this.definition.timeline||{}),animation:this.attackAnimation,followupAnimation:this.definition.followupAnimation,sourceRange:this.definition.sourceRange});this.skillTimeline=result.timeline||null;if(!result.activated)this.completeSkillState();return result;}
 completeSkillState(){this.skillTimeline=null;if(this.currentState!==EnemyRuntimeState.DEAD)this.changeState(this.preSkillState===EnemyRuntimeState.SKILL?EnemyRuntimeState.MOVING:this.preSkillState);}
 buildSkillContext(){const port=this.skillManager&&this.skillManager.effectPort;const unitRegistry=port&&port.unitRegistry;const enemyManager=port&&port.enemyManager;const units=unitRegistry?[...unitRegistry.soldiers.values()]:[];const alliedEnemies=enemyManager?[...enemyManager.enemies.values()].filter(e=>e!==this&&e.isPlayerLane===this.isPlayerLane):[];return{boss:this,owner:this,targets:units,alliedEnemies,enemyManager,unitRegistry,range:this.skillRange,presentation:this.skillManager.presentation};}
 beginDeath(){if(this.deathStarted)return;super._beginDeath();const generation=this._lifecycleGeneration;this.presentation.playDeath(this,'#000000',()=>{if(generation!==this._lifecycleGeneration||this.inPool)return;this.gameOver();});}
 gameOver(){if(this.inPool||this.__InPool)return false;if(this.skillManager)this.skillManager.removeOwner(this.id);const visual=this.visual,animation=this.animation;const result=super.gameOver();if(animation){this.presentation.resetAnimation(animation);if(typeof animation.removeSelf==='function')animation.removeSelf();if(typeof animation.recover==='function')animation.recover();}this.animation=null;this.skill=null;this.skillTimeline=null;this.skillElapsedMs=0;if(visual)this.objectPool.recoverByKey(this.visualPoolKey,visual);return result;}
}
module.exports={BossBase};
