'use strict';
module.exports = {
  ...require('./ProjectileMath'),
  ...require('./HitEnemyStrategy'),
  ...require('./TargetEnemyBezierMovement'),
  ...require('./ProjectileBase'),
  ...require('./ProjectileFactory'),
  ...require('./ProjectileManager'),
  ...require('./SimpleDynamicArrow'),
  ...require('./movement'),
  ...require('./hit-strategies'),
  ...require('./types/EagleArrow'),
  ...require('./types/FireArrow'),
  ...require('./types/HuoFengHuang'),
  ...require('./types/PikeSnakeBullet'),
  ...require('./types/LightningChain'),
  ...require('./types/ShenBiArrow'),
  // 提案 ④b 新增 16 弹种
  ...require('./types/SimpleHitAreaBullet'),
  ...require('./types/KnifeBullet'),
  ...require('./types/PikeBullet'),
  ...require('./types/StaticFireBall'),
  ...require('./types/VirtualBullet'),
  ...require('./types/SwordBullet'),
  ...require('./types/StarBullet'),
  ...require('./types/FireDragonArrow'),
  ...require('./types/GroundSpikeBullet'),
  ...require('./types/FireExplosiveArrow'),
  ...require('./types/DaoQiBullet'),
  ...require('./types/AttachCustomShapeBullet'),
  ...require('./types/SimpleHitBullet'),
  ...require('./types/LiHuaBullet'),
  ...require('./types/LightningArrow'),
  ...require('./types/FlyPike'),
};
