require("weapp-adapter.js");
//
require("libs/laya.core.js");
//
require("libs/laya.webgl_2D.js");
//
require("libs/laya.ui.js");
//
require("libs/laya.trailCommon.js");
//
require("libs/laya.trail2D.js");
//
require("libs/spine-core-3.7.js");
//
require("libs/laya.spine.js");
//
require("libs/laya.adapter-weixin.js");
//

//
require("js/bundle.js");
//
require("js/index.js");