
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.boss
{
/// <summary>
/// Boss技能时间轴
/// </summary>
public sealed partial class Timeline : Luban.BeanBase
{
    public Timeline(ByteBuf _buf) 
    {
        EffectAtMs = _buf.ReadInt();
        CompleteAtMs = _buf.ReadInt();
    }

    public static Timeline DeserializeTimeline(ByteBuf _buf)
    {
        return new boss.Timeline(_buf);
    }

    /// <summary>
    /// 特效触发毫秒
    /// </summary>
    public readonly int EffectAtMs;
    /// <summary>
    /// 完成毫秒
    /// </summary>
    public readonly int CompleteAtMs;
   
    public const int __ID__ = 1883797954;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "effectAtMs:" + EffectAtMs + ","
        + "completeAtMs:" + CompleteAtMs + ","
        + "}";
    }
}
}

