'use strict';
const { BattleInputCommandType }=require('./BattleInputCommand');
const { UnitContainerType }=require('../units/UnitBase');
class BattleInputController{
 constructor({deckManager,economy,unitRegistry,mergeService,mapTileManager,logger=console}={}){if(!deckManager||!economy||!unitRegistry||!mergeService)throw new TypeError('BattleInputController missing dependencies');Object.assign(this,{deckManager,economy,unitRegistry,mergeService,mapTileManager,logger});this.activeDrag=null;this.started=false;}
 init(){}
 startGame(){this.started=true;this.activeDrag=null;}
 validatePlacement(side,x,y){const map=this.unitRegistry.gameData.map;if(!map.isBuildableForSide(side,x,y))return{valid:false,reason:'士兵不能放到该格子'};if(this.mapTileManager&&!this.mapTileManager.canPlace(side,x,y))return{valid:false,reason:'地块不可用'};if(this.unitRegistry.hasBattleOccupant(side,x,y))return{valid:false,reason:'格子已被占用'};return{valid:true};}
 purchaseAndPlace({side=true,slot=0,gridX,gridY}={}){if(!this.started)return{success:false,reason:'输入控制器未启动'};const card=this.deckManager.getCard(side,slot);if(!card)return{success:false,reason:'卡牌不存在'};const check=this.validatePlacement(side,gridX,gridY);if(!check.valid)return{success:false,reason:check.reason};const payment=this.economy.payRecruit(side,card);if(!payment.success)return payment;let unit;try{unit=this.unitRegistry.createUnit(UnitContainerType.BATTLE,card.text,side,gridX,gridY,card.level);}catch(error){this.economy.award(side,payment.amount,'rollback');return{success:false,reason:error.message};}this.deckManager.consume(side,slot);return{success:true,unit,card,cost:payment.amount};}
 execute(command){const p=command.payload||{};switch(command.type){case BattleInputCommandType.PURCHASE_AND_PLACE:return this.purchaseAndPlace(p);case BattleInputCommandType.REFRESH:return this.deckManager.refresh(p.side!==false);case BattleInputCommandType.MERGE_UNITS:return this.mergeService.merge(p.sourceId,p.targetId);case BattleInputCommandType.MOVE_UNIT:return this.moveUnit(p);case BattleInputCommandType.BEGIN_DRAG:this.activeDrag={...p};return{success:true};case BattleInputCommandType.MOVE_DRAG:if(!this.activeDrag)return{success:false,reason:'未开始拖拽'};Object.assign(this.activeDrag,p);return{success:true};case BattleInputCommandType.COMMIT_PLACEMENT:return this.activeDrag?this.purchaseAndPlace({...this.activeDrag,...p}):{success:false,reason:'未开始拖拽'};case BattleInputCommandType.CANCEL_DRAG:this.activeDrag=null;return{success:true};default:throw new Error(`Unsupported input command ${command.type}`);}}
 moveUnit({unitId,gridX,gridY}={}){const unit=this.unitRegistry.getUnit(unitId);if(!unit)return{success:false,reason:'单位不存在'};const check=this.validatePlacement(unit.side,gridX,gridY);if(!check.valid)return{success:false,reason:check.reason};unit.setPlacement(UnitContainerType.BATTLE,gridX,gridY);this.unitRegistry.reposition(unit);return{success:true,unit};}
 cancelDrag(){this.activeDrag=null;}
 gameOver(){this.started=false;this.cancelDrag();}
}
module.exports={BattleInputController};
